<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AppScenariosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('app.scenarios')->delete();
        
        \DB::table('app.scenarios')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'screen_id' => 4,
                'code' => 'magnam',
                'type' => 'hidden',
                'title' => 'Eaque',
                'tooltip' => NULL,
                'description' => 'Ut consequatur porro excepturi adipisci. Illum ad quia commodi ea et et. Cumque repellat vel aut laboriosam.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'screen_id' => 5,
                'code' => 'odio',
                'type' => 'hidden',
                'title' => 'Ut',
                'tooltip' => NULL,
                'description' => 'Qui magnam alias qui illum dolorem amet. Veniam praesentium earum voluptatum. Quia illo adipisci laudantium unde voluptas praesentium. Incidunt voluptas qui et non assumenda quae ut.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'screen_id' => 4,
                'code' => 'provident',
                'type' => 'hidden',
                'title' => 'Deleniti Et',
                'tooltip' => NULL,
                'description' => 'Beatae necessitatibus velit odit consequatur sed. Error dolorum est nostrum similique aut natus. Maxime vitae molestiae velit. Et vero ab soluta harum repellendus.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'screen_id' => 3,
                'code' => 'temporibus',
                'type' => 'hidden',
                'title' => 'Ipsam Quaerat',
                'tooltip' => NULL,
                'description' => 'Similique itaque temporibus sit quas est et voluptas minus. Id est placeat officiis. Incidunt pariatur architecto totam ipsa velit soluta.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'screen_id' => 3,
                'code' => 'neque',
                'type' => 'hidden',
                'title' => 'Ut Ut',
                'tooltip' => NULL,
                'description' => 'Quae porro ut id. Est magni temporibus et est amet possimus exercitationem. Aut deserunt commodi mollitia commodi.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'screen_id' => 2,
                'code' => 'saepe',
                'type' => 'hidden',
                'title' => 'Ut Error',
                'tooltip' => NULL,
                'description' => 'Consequatur harum reprehenderit explicabo libero assumenda. Omnis harum ut et saepe rerum fugit. Dolorum velit impedit possimus molestias minima rerum quis.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'screen_id' => 6,
                'code' => 'ut',
                'type' => 'hidden',
                'title' => 'Dignissimos Quaerat',
                'tooltip' => NULL,
                'description' => 'Ex voluptas voluptas culpa neque nihil qui illum. Dignissimos aspernatur aut accusantium iste omnis aut dolor. Animi et ipsum impedit et officiis adipisci. Qui commodi est neque optio distinctio.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'screen_id' => 2,
                'code' => 'sint',
                'type' => 'hidden',
                'title' => 'Blanditiis',
                'tooltip' => NULL,
                'description' => 'Amet ad blanditiis maxime voluptatem. Optio sit a rerum sed possimus aspernatur commodi impedit. Dolor et ipsam molestiae illum iusto.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'screen_id' => 4,
                'code' => 'qui',
                'type' => 'hidden',
                'title' => 'Assumenda',
                'tooltip' => NULL,
                'description' => 'At corrupti eos totam et. Necessitatibus sed dolorem cum quia aperiam fugiat labore. Voluptatem suscipit quia rerum aut et quisquam.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'screen_id' => 5,
                'code' => 'velit',
                'type' => 'hidden',
                'title' => 'Corrupti Molestiae',
                'tooltip' => NULL,
                'description' => 'Alias saepe iure commodi optio nihil. Doloremque enim odio consectetur tenetur voluptatibus est sit provident. Aut a deserunt nam deleniti rerum qui.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'screen_id' => 3,
                'code' => 'dolorum',
                'type' => 'hidden',
                'title' => 'Laborum Consequuntur',
                'tooltip' => NULL,
                'description' => 'Quis eum quia excepturi et. Eveniet dolorum magnam eos consequatur dignissimos. Quia soluta iure nobis totam sint ullam.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'screen_id' => 1,
                'code' => 'aperiam',
                'type' => 'hidden',
                'title' => 'Neque Et',
                'tooltip' => NULL,
                'description' => 'Qui iste tempora deleniti qui velit. Est sequi dolor facilis quisquam non est consequatur. In autem minus adipisci tenetur. Neque culpa nemo culpa assumenda incidunt.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'screen_id' => 6,
                'code' => 'iure',
                'type' => 'hidden',
                'title' => 'Eaque Incidunt',
                'tooltip' => NULL,
                'description' => 'Ratione expedita perspiciatis earum qui nesciunt consequatur. Deleniti quia soluta consequatur sit ratione qui.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'screen_id' => 1,
                'code' => 'et',
                'type' => 'hidden',
                'title' => 'Aut Consequatur',
                'tooltip' => NULL,
                'description' => 'Voluptatibus et dolorem ipsam error et et quisquam. Mollitia nulla tenetur aut dolor veritatis nemo. Velit similique non consequatur et quaerat. Ab quo veritatis voluptate qui repellendus.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:40:32',
                'updated_at' => '2025-03-16 16:40:32',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'screen_id' => 11,
                'code' => 'blanditiis',
                'type' => 'hidden',
                'title' => 'Blanditiis',
                'tooltip' => NULL,
                'description' => 'Voluptatem eius aliquid quae vel ducimus quaerat reiciendis. Aliquam nemo quis fugiat tenetur enim minus. Pariatur accusamus repudiandae repellat.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'screen_id' => 10,
                'code' => 'delectus',
                'type' => 'hidden',
                'title' => 'Delectus',
                'tooltip' => NULL,
                'description' => 'Suscipit asperiores quisquam sit vel ut sed in. Libero rerum dolorem omnis ut et aut iste. Est reiciendis ut aliquid aperiam vel nulla ipsam iusto. Praesentium consequatur natus facere in.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'screen_id' => 7,
                'code' => 'occaecati',
                'type' => 'hidden',
                'title' => 'Occaecati',
                'tooltip' => NULL,
                'description' => 'Ex similique voluptatibus quisquam ipsam officiis. Quia architecto quo rerum. Aut mollitia veritatis illum.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'screen_id' => 8,
                'code' => 'veritatis-rerum',
                'type' => 'hidden',
                'title' => 'Veritatis Rerum',
                'tooltip' => NULL,
                'description' => 'Quasi omnis deleniti aut id enim. Voluptatem soluta repellat culpa velit et eveniet quae. Et odit dolores iusto similique ipsum sint eum ut. Ullam sit praesentium aut asperiores ipsum aut qui itaque.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'screen_id' => 8,
                'code' => 'corrupti-saepe',
                'type' => 'hidden',
                'title' => 'Corrupti Saepe',
                'tooltip' => NULL,
                'description' => 'Incidunt sed nulla qui. Veniam mollitia sed quidem maxime. Consequatur modi sint sit eos nihil autem hic eveniet. Dolorum et quasi iusto temporibus sit cumque.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'screen_id' => 10,
                'code' => 'aut',
                'type' => 'hidden',
                'title' => 'Aut',
                'tooltip' => NULL,
                'description' => 'Pariatur in quas quis deleniti. Blanditiis qui explicabo architecto autem minima. Libero est delectus iusto ab impedit. Id repellendus debitis facilis enim iste illum. Enim dolor quaerat deserunt.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'screen_id' => 7,
                'code' => 'itaque-ipsam',
                'type' => 'hidden',
                'title' => 'Itaque Ipsam',
                'tooltip' => NULL,
                'description' => 'Atque iusto mollitia omnis. Reiciendis nesciunt ducimus fuga. Deleniti quod eos iure non. Ea eveniet nobis enim officiis.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'screen_id' => 7,
                'code' => 'est',
                'type' => 'hidden',
                'title' => 'Est',
                'tooltip' => NULL,
                'description' => 'Facilis enim quo ab molestias eum sed eos autem. Quaerat at et dolorem ad non. Quis voluptatem voluptatem voluptas quibusdam illo.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'screen_id' => 11,
                'code' => 'animi',
                'type' => 'hidden',
                'title' => 'Animi',
                'tooltip' => NULL,
                'description' => 'Et ullam eligendi deleniti impedit et accusantium. Et sit eos maxime quidem ex qui. Sint aut tenetur optio quo qui.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'screen_id' => 11,
                'code' => 'rerum-voluptatum',
                'type' => 'hidden',
                'title' => 'Rerum Voluptatum',
                'tooltip' => NULL,
                'description' => 'Qui atque est excepturi nulla vel amet. Omnis voluptates nihil dolor quisquam. Optio et est iusto alias et impedit.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'screen_id' => 11,
                'code' => 'atque-nemo',
                'type' => 'hidden',
                'title' => 'Atque Nemo',
                'tooltip' => NULL,
                'description' => 'Et velit sed reprehenderit occaecati. Illum nihil dolorem sunt.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'screen_id' => 7,
                'code' => 'consequatur-rerum',
                'type' => 'hidden',
                'title' => 'Consequatur Rerum',
                'tooltip' => NULL,
                'description' => 'Tenetur possimus dolor incidunt et. Mollitia eligendi et aut accusantium aut aut placeat. In ut vel qui labore sit culpa alias excepturi.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'screen_id' => 12,
                'code' => 'tempora-quod',
                'type' => 'hidden',
                'title' => 'Tempora Quod',
                'tooltip' => NULL,
                'description' => 'Magnam et consequuntur dolorum eaque. Officiis voluptatem ipsa illum architecto voluptas quia sit.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'screen_id' => 9,
                'code' => 'quos-dolor',
                'type' => 'hidden',
                'title' => 'Quos Dolor',
                'tooltip' => NULL,
                'description' => 'Non hic earum ea mollitia maxime rerum quis laboriosam. Dicta dolorem accusantium et. Qui veritatis est harum quod. Nobis ut perferendis vel voluptatem esse sapiente.',
                'is_default' => false,
                'constants' => NULL,
                'active' => NULL,
                'created_at' => '2025-03-16 16:47:12',
                'updated_at' => '2025-03-16 16:47:12',
            ),
        ));
        
        
    }
}